### ISSUE TITLE
prototype.registerCallback is not a function

### ISSUE THREAD

**Issue by henryheinemann** [hejty/social-media-icons#2]
In line 73, where the Polymer element is defined, a callback is used which is deprecated and does not work with the most recent version. 

`Polymer('social-media-icons', {`

should be

`Polymer({ is: 'social-media-icons',`

That gets rid of the error for me. However the icons are still not displayed. So I'm kind of stuck here...

**Comment by httpstersk** [comment]
Please check out a new version of `social-media-icons` which is Polymer 1.0-friendly!
