### ISSUE TITLE
open link in new tab

### ISSUE THREAD

**Issue by ghost** [hejty/social-media-icons#4]
This is really awesome thanks 

so it opens a new browser tab.

Needs to support:  **target="_blank"**

Example:

```
Twitter: <social-media-icons icon="twitter" color="#bada55" size="32" href="https://twitter.com/" target="_blank" **></social-media-icons>
```

**Comment by httpstersk** [comment]
Hello @gedw99! Check out new version of `social-media-icons` element. I added a new attribute `newTab` that opens the linked icon on a new browser tab.
