### ISSUE TITLE
Icons are not clickable on the white space

### ISSUE THREAD

**Issue by sasivarnan** [hejty/social-media-icons#7]
The white area in the svg are not clickable making href attribute not usable.
See your demo link (http://hejty.github.io/demos/social-media-icons/).

The white space in the octa-cat is not clickable.

**Comment by httpstersk** [comment]
In a new version I got rid of `href` attribute totally, you can (and you should) wrap your `social-media-icons` in `a` tag instead - it will solve that "whitespace" problem ;)

**Comment by sasivarnan** [comment]
@hejty  Thanks a lot
